// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVTuY1hlFtTGuqi3V5Lvhg4FoDCeumMmc',
    appId: '1:643541215150:web:4c03ce6f7339b758c88a3f',
    messagingSenderId: '643541215150',
    projectId: 'styla-01',
    authDomain: 'styla-01.firebaseapp.com',
    storageBucket: 'styla-01.firebasestorage.app',
    measurementId: 'G-PPPKSXDJCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVeE6kz5Ow-GwlyWngzLCSRdH16LR9uW4',
    appId: '1:643541215150:android:fd7e2484b4ce766dc88a3f',
    messagingSenderId: '643541215150',
    projectId: 'styla-01',
    storageBucket: 'styla-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1CDauaeCKWPfTvg3DRGbd1sYMBhBWThY',
    appId: '1:643541215150:ios:caf476dc80b48376c88a3f',
    messagingSenderId: '643541215150',
    projectId: 'styla-01',
    storageBucket: 'styla-01.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1CDauaeCKWPfTvg3DRGbd1sYMBhBWThY',
    appId: '1:643541215150:ios:caf476dc80b48376c88a3f',
    messagingSenderId: '643541215150',
    projectId: 'styla-01',
    storageBucket: 'styla-01.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVTuY1hlFtTGuqi3V5Lvhg4FoDCeumMmc',
    appId: '1:643541215150:web:c25a8efe1cb4fb0ec88a3f',
    messagingSenderId: '643541215150',
    projectId: 'styla-01',
    authDomain: 'styla-01.firebaseapp.com',
    storageBucket: 'styla-01.firebasestorage.app',
    measurementId: 'G-NWP1HGVDE2',
  );

}